# Generated by Django 5.0.1 on 2024-01-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variation_variation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('variation_category', 'variation_value')},
        ),
    ]
