# Generated by Django 5.0.1 on 2024-01-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_variation_variation_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'variation_category', 'variation_value')},
        ),
    ]
