# Generated by Django 5.0.1 on 2024-01-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000248F9A1FEC0>', max_length=200),
        ),
    ]
