# Generated by Django 5.0.1 on 2024-01-25 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_is_merchant_account_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantUser',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_details', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.TextField()),
                ('is_added_by_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000021DF2C1FD80>', max_length=200),
        ),
    ]
