# Generated by Django 5.0.1 on 2024-02-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_uid_addressbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='address_line1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='addressbook',
            old_name='address_line2',
            new_name='address_line_2',
        ),
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001AC13C81C60>', max_length=200),
        ),
    ]
