# Generated by Django 5.0.1 on 2024-02-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_address_line1_addressbook_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000027367361C60>', max_length=200),
        ),
    ]
