# Generated by Django 5.0.1 on 2024-02-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_uid_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000012416B01C60>', max_length=200),
        ),
    ]
