# Generated by Django 5.0.1 on 2024-02-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_account_uid_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000010A09B11C60>', max_length=200),
        ),
    ]
