# Generated by Django 5.0.1 on 2024-01-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='c_name',
            new_name='cat_name',
        ),
    ]
