# Generated by Django 5.0.1 on 2024-01-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_is_active'),
    ]

    operations = [
    ]
