# Generated by Django 5.0.1 on 2024-01-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_variations'),
    ]

    operations = [
    ]
