# Generated by Django 5.0.1 on 2024-01-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20240129_1934'),
    ]

    operations = [
    ]
