# Generated by Django 5.0.1 on 2024-02-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], default='Processing', max_length=10),
        ),
    ]
